# Generated by Django 3.2.14 on 2022-07-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField()),
                ('headline', models.CharField(max_length=500)),
                ('unique_id', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=500)),
                ('related', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=50)),
                ('summary', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=50)),
            ],
        ),
    ]
