# Generated by Django 4.0.6 on 2022-07-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyNew',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField()),
                ('headline', models.CharField(max_length=500)),
                ('unique_id', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=500)),
                ('related', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=50)),
                ('summary', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
