# Generated by Django 4.0.6 on 2022-07-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_companynew_delete_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companynew',
            name='related',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='companynew',
            name='source',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='companynew',
            name='unique_id',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='companynew',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
