# Generated by Django 4.0.6 on 2022-07-11 18:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4, unique=True)),
                ('users_subscribed', models.ManyToManyField(null=True, related_name='subscribers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
