# Generated by Django 4.0.6 on 2022-07-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220712_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketinterest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
